### ISSUE TITLE
Paimon and Cyno

### ISSUE THREAD

**Issue by olibeniron** [tmarenko/GenshinImpact_PaimonShutUp#11]
Hello! Same person who'd first suggested adding more languages for the programm. I've been using your tool since then, and it truly brought me peace. However, with Sumeru release, there seemed to be a little problem with name recognition. It wasn't as pronounced until I touched upon Cyno's personal quest, now it gets in the way.

Cyno and Paimon names spelled very similar in Russian "Паймон | Сайно" so the tool mistakes them and mutes Cyno on many occasions. Is it possible to overcome it? I've been switching game to English whenever Cyno turns up in quests, but that's not the best solution since my reading speed significantly drops that way.

**Comment by tmarenko** [comment]
Are you playing with low resolution maybe? The Levenshtein difference between "Паймон" and "Сайно" is 3 and currently the script allows only 2 errors in the name. So could be Tesseract is recognizing Cyno's name with errors as well.
Anyway, at least I should have check the difference by Paimon's name, so it's fixed in https://github.com/tmarenko/GenshinImpact_PaimonShutUp/commit/303d437aa48823250bd4ada030dbb0d936d11760

Please try new build: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/4963033165

If this won't help then I could make the "how many wrong letters is allowed" varible (by lowering [overlap param](https://github.com/tmarenko/GenshinImpact_PaimonShutUp/blob/main/source/tesseract.h#L27)) into the config file. So you could have more strict rules to catch only "Paimon" text.

**Comment by olibeniron** [comment]
My resolution is 1920x1080 fullscreen with 16:9 screen ratio.
Thank you, I'll try the new build today.

**Comment by olibeniron** [comment]
Ah, no, it still mutes him as well. Even more vigorously than before.

**Comment by tmarenko** [comment]
I lowered allowed errors in https://github.com/tmarenko/GenshinImpact_PaimonShutUp/commit/795285fbd1cafe7ad634e7d7e95e1bf896a9335e

Please try new build: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/4971602069

If this won't help I'll check Russian translation manually on my PC.
And probably will think about adding unit-tests for different languages and character names.

**Comment by olibeniron** [comment]
So far it works! I'll continue to observe it through the questline, but the latest build seemed to fix the problem. I'll report how it went at the end of the day.

**Comment by olibeniron** [comment]
Yes, it no longer mistakes Paimon and Cyno and works flawlessly. Thank you very much for the fix.

**Comment by tmarenko** [comment]
Added as configuration option in https://github.com/tmarenko/GenshinImpact_PaimonShutUp/commit/4aac275397282c6cfe5bf904fe31da73242bbd74
Released in [1.5.0](https://github.com/tmarenko/GenshinImpact_PaimonShutUp/releases/tag/1.5.0)
